name: DeepSpeech

on:
  push:
    branches:
      - feature/deepspeech
#      - master
#    paths:
#      - '.github/workflows/deepspeech.yml'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DeepSpeech
        uses: actions/checkout@v2
        with:
         repository: OpenASR/DeepSpeech-Java-Bindings
         path: DeepSpeech-Java-Bindings

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

#        wget https://github.com/mozilla/DeepSpeech/archive/v0.7.1.tar.gz
#        https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cpu.linux.tar.xz
#        https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cuda.win.tar.xz
      - name: Download libdeepspeech
#        working-directory: DeepSpeech-Java-Bindings/DeepSpeech-jni
        run: |
          wget -q https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cpu.linux.tar.xz
          tar -xf native_client.amd64.cpu.linux.tar.xz && rm native_client.amd64.cpu.linux.tar.xz
          mkdir -p DeepSpeech-Java-Bindings/DeepSpeech-jni/libs/linux && mv libdeepspeech.so $_/libdeepspeech_cpu.so
#          pwd
#          ls -al DeepSpeech-Java-Bindings/DeepSpeech-jni/libs/linux

      - name: Build libdeepspeech-jni
        working-directory: DeepSpeech-Java-Bindings/DeepSpeech-jni
        run: |
          sed -i "s/set(CUDA_CONFIGURATION .*)/set(CUDA_CONFIGURATION FALSE)/" CMakeLists.txt
          sed -i "s/set(PLATFORM .*)/set(PLATFORM linux)/" CMakeLists.txt
          cmake build .
          make
          mv libdeepspeech-jni.so libs/linux/libdeepspeech-jni_cpu.so

      - name: Build libdeepspeech-java.jar
        working-directory: DeepSpeech-Java-Bindings/libdeepspeech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gradle publish -x test

      - name: Archive linux zip
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: DeepSpeech-Java-Bindings/DeepSpeech-jni/libs/linux

  idear:
    needs: linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: linux

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        run: |
          ls -al linux
          mkdir --parents src/main/resources/natives/UNIX; mv linux $_
          ./gradlew buildPlugin

# now we have:
#  DeepSpeech-jni
#   libs/
#     linux/
#       libdeepspeech_cpu.so
#       libdeepspeech_cuda.so
#       libdeepspeech-jni_cpu
#     windows/
#       libdeepspeech_cpu.so
#       libdeepspeech_cuda.so

#set(CUDA_CONFIGURATION FALSE)
