name: DeepSpeech

on:
  push:
    branches:
      - feature/deepspeech
#      - master

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DeepSpeech
        uses: actions/checkout@v2
        with:
         repository: GommeAntiLegit/DeepSpeech-Java-Bindings

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

#        wget https://github.com/mozilla/DeepSpeech/archive/v0.7.1.tar.gz
#        https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cpu.linux.tar.xz
#        https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cuda.win.tar.xz
      - name: Download libdeepspeech
        working-directory: DeepSpeech-jni
        run: |
          mkdir -p libs/linux && cd $_
          wget -q https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/native_client.amd64.cpu.linux.tar.xz
          tar -xf native_client.amd64.cpu.linux.tar.xz && rm native_client.amd64.cpu.linux.tar.xz
          mv libdeepspeech.so libdeepspeech_cpu.so

      - name: Build libdeepspeech-java.jar
        working-directory: libdeepspeech
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "2i\
              id 'maven-publish'\
          " build.gradle
          tee -a build.gradle << END

          publishing {
            repositories {
              maven {
                name "GitHubPackages"
                url "https://maven.pkg.github.com/" + System.getenv("GITHUB_REPOSITORY")
                credentials {
                  username System.getenv("GITHUB_ACTOR")
                  password System.getenv("GITHUB_TOKEN")
                }
              }
            }
          }
          END
          gradle publish -x test

      - name: Build libdeepspeech-jni
        working-directory: DeepSpeech-jni
        run: |
          sed -i "s/set(CUDA_CONFIGURATION .*)/set(CUDA_CONFIGURATION FALSE)/" CMakeLists.txt
          sed -i "s/set(PLATFORM .*)/set(PLATFORM linux)/" CMakeLists.txt
          CXXFLAGS=-isystem\ libs/linux/ cmake build .
          make
          ls -al
          ls -al cmake-build-release

#set(CUDA_CONFIGURATION FALSE)
